# Created by ftools channels (Bosma Interactive AB)
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Filestar.Filestar
PackageVersion: 30.1.0.0
MinimumOSVersion: 10.0.14393.0
InstallerType: inno
UpgradeBehavior: install
Commands:
- filestarcli
FileExtensions:
- recipe
ProductCode: '{A7472187-20F3-43DD-B331-C52604BAB494}_is1'
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://release.filestar.com/releases/30.1.0.0/Filestar.30.1.0.0.win-x64.exe
  InstallerSha256: 023CB3546D6F09E50C53EC185328B7182F7C7CFC998621601F2A3E5AB30EFDBD
  InstallerSwitches:
    Custom: /CURRENTUSER /channel=winget
- Architecture: x64
  Scope: machine
  InstallerUrl: https://release.filestar.com/releases/30.1.0.0/Filestar.30.1.0.0.win-x64.exe
  InstallerSha256: 023CB3546D6F09E50C53EC185328B7182F7C7CFC998621601F2A3E5AB30EFDBD
  InstallerSwitches:
    Custom: /ALLUSERS /channel=winget
- Architecture: x86
  Scope: user
  InstallerUrl: https://release.filestar.com/releases/30.1.0.0/Filestar.30.1.0.0.win-x86.exe
  InstallerSha256: 791EECB808A99EAA06EC4C0FC603AA137D96A536CC62D7DB1439EBACE6599283
  InstallerSwitches:
    Custom: /CURRENTUSER /channel=winget
- Architecture: x86
  Scope: machine
  InstallerUrl: https://release.filestar.com/releases/30.1.0.0/Filestar.30.1.0.0.win-x86.exe
  InstallerSha256: 791EECB808A99EAA06EC4C0FC603AA137D96A536CC62D7DB1439EBACE6599283
  InstallerSwitches:
    Custom: /ALLUSERS /channel=winget
ManifestType: installer
ManifestVersion: 1.10.0
