# Created by ftools channels (Bosma Interactive AB)
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Filestar.Filestar
PackageVersion: 30.0.0.0
MinimumOSVersion: 10.0.14393.0
InstallerType: inno
UpgradeBehavior: install
Commands:
- filestarcli
FileExtensions:
- recipe
ProductCode: '{A7472187-20F3-43DD-B331-C52604BAB494}_is1'
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://release.filestar.com/releases/30.0.0.0/Filestar.30.0.0.0.win-x64.exe
  InstallerSha256: FF8D1C7AC495ED91CE879DC79005988C802372E7977171DF8A3F280C372BF9D3
  InstallerSwitches:
    Custom: /CURRENTUSER /channel=winget
- Architecture: x64
  Scope: machine
  InstallerUrl: https://release.filestar.com/releases/30.0.0.0/Filestar.30.0.0.0.win-x64.exe
  InstallerSha256: FF8D1C7AC495ED91CE879DC79005988C802372E7977171DF8A3F280C372BF9D3
  InstallerSwitches:
    Custom: /ALLUSERS /channel=winget
- Architecture: x86
  Scope: user
  InstallerUrl: https://release.filestar.com/releases/30.0.0.0/Filestar.30.0.0.0.win-x86.exe
  InstallerSha256: 4BF4EAF53E5389436C17CD76178208C765AD709D6C5F827DB099854B0E7499DF
  InstallerSwitches:
    Custom: /CURRENTUSER /channel=winget
- Architecture: x86
  Scope: machine
  InstallerUrl: https://release.filestar.com/releases/30.0.0.0/Filestar.30.0.0.0.win-x86.exe
  InstallerSha256: 4BF4EAF53E5389436C17CD76178208C765AD709D6C5F827DB099854B0E7499DF
  InstallerSwitches:
    Custom: /ALLUSERS /channel=winget
ManifestType: installer
ManifestVersion: 1.10.0
